package com.warrantyvault.ui

import androidx.compose.ui.graphics.Color

enum class ThemeConfig(
    val key: String,
    val label: String,
    val subtitle: String,
    val accentLabel: String,
    val night: Color,
    val nightRaised: Color,
    val glass: Color,
    val glassStrong: Color,
    val glassBorder: Color,
    val accent: Color,
    val accentSecondary: Color,
    val accentTertiary: Color,
    val text: Color,
    val textMuted: Color,
    val materialPrimary: Color,
    val materialOnPrimary: Color,
    val materialPrimaryContainer: Color,
    val materialOnPrimaryContainer: Color,
    val materialSecondary: Color,
    val materialOnSecondary: Color,
    val materialSecondaryContainer: Color,
    val materialOnSecondaryContainer: Color,
    val materialTertiary: Color,
    val materialOnTertiary: Color,
    val materialTertiaryContainer: Color,
    val materialOnTertiaryContainer: Color,
    val materialSurface: Color,
    val materialOnSurface: Color,
    val materialSurfaceVariant: Color,
    val materialOnSurfaceVariant: Color,
    val materialOutline: Color
) {
    Vault(
        key = "vault",
        label = "Vault",
        subtitle = "Mint and dark glass",
        accentLabel = "Mint",
        night = Color(0xFF121417),
        nightRaised = Color(0xFF1A1D22),
        glass = Color(0x47262B33),
        glassStrong = Color(0x66313843),
        glassBorder = Color(0x33E7EDF4),
        accent = Color(0xFF86D6A6),
        accentSecondary = Color(0xFF85B9D8),
        accentTertiary = Color(0xFFE1BF73),
        text = Color(0xFFE9ECE8),
        textMuted = Color(0xFFB7BDB5),
        materialPrimary = Color(0xFF86D6A6),
        materialOnPrimary = Color(0xFF102219),
        materialPrimaryContainer = Color(0xFF244934),
        materialOnPrimaryContainer = Color(0xFFD5F4DF),
        materialSecondary = Color(0xFF85B9D8),
        materialOnSecondary = Color(0xFF10212B),
        materialSecondaryContainer = Color(0xFF203D4D),
        materialOnSecondaryContainer = Color(0xFFD6ECF8),
        materialTertiary = Color(0xFFE49788),
        materialOnTertiary = Color(0xFF321A16),
        materialTertiaryContainer = Color(0xFF53322C),
        materialOnTertiaryContainer = Color(0xFFFFDCD4),
        materialSurface = Color(0xFF1A1D22),
        materialOnSurface = Color(0xFFE9ECE8),
        materialSurfaceVariant = Color(0xFF30363F),
        materialOnSurfaceVariant = Color(0xFFB7BDB5),
        materialOutline = Color(0x33E7EDF4)
    ),
    Midnight(
        key = "midnight",
        label = "Midnight",
        subtitle = "Deep indigo and violet",
        accentLabel = "Violet",
        night = Color(0xFF0D0F17),
        nightRaised = Color(0xFF161824),
        glass = Color(0x47252A3A),
        glassStrong = Color(0x66313852),
        glassBorder = Color(0x33A8B5E0),
        accent = Color(0xFF9DA6F0),
        accentSecondary = Color(0xFF7EC8E3),
        accentTertiary = Color(0xFFD4A0E8),
        text = Color(0xFFE8E9F0),
        textMuted = Color(0xFFB2B6C5),
        materialPrimary = Color(0xFF9DA6F0),
        materialOnPrimary = Color(0xFF14172A),
        materialPrimaryContainer = Color(0xFF2A2E52),
        materialOnPrimaryContainer = Color(0xFFDCDEFB),
        materialSecondary = Color(0xFF7EC8E3),
        materialOnSecondary = Color(0xFF0E1F2A),
        materialSecondaryContainer = Color(0xFF1E3D4A),
        materialOnSecondaryContainer = Color(0xFFD4EDF8),
        materialTertiary = Color(0xFFD4A0E8),
        materialOnTertiary = Color(0xFF2E173A),
        materialTertiaryContainer = Color(0xFF4F2D5A),
        materialOnTertiaryContainer = Color(0xFFF2DCFC),
        materialSurface = Color(0xFF161824),
        materialOnSurface = Color(0xFFE8E9F0),
        materialSurfaceVariant = Color(0xFF2C2F40),
        materialOnSurfaceVariant = Color(0xFFB2B6C5),
        materialOutline = Color(0x33A8B5E0)
    ),
    Ember(
        key = "ember",
        label = "Ember",
        subtitle = "Warm amber and copper",
        accentLabel = "Amber",
        night = Color(0xFF161210),
        nightRaised = Color(0xFF1F1A16),
        glass = Color(0x473A3028),
        glassStrong = Color(0x664A3D33),
        glassBorder = Color(0x33E0C8A8),
        accent = Color(0xFFE8B86A),
        accentSecondary = Color(0xFFD48B7A),
        accentTertiary = Color(0xFFA8C87A),
        text = Color(0xFFF0EAE3),
        textMuted = Color(0xFFC5BAA8),
        materialPrimary = Color(0xFFE8B86A),
        materialOnPrimary = Color(0xFF2A1E0E),
        materialPrimaryContainer = Color(0xFF4A3520),
        materialOnPrimaryContainer = Color(0xFFFCF0DA),
        materialSecondary = Color(0xFFD48B7A),
        materialOnSecondary = Color(0xFF2A1510),
        materialSecondaryContainer = Color(0xFF4A2E26),
        materialOnSecondaryContainer = Color(0xFFFCE0D4),
        materialTertiary = Color(0xFFA8C87A),
        materialOnTertiary = Color(0xFF1A260E),
        materialTertiaryContainer = Color(0xFF354620),
        materialOnTertiaryContainer = Color(0xFFE4F0D4),
        materialSurface = Color(0xFF1F1A16),
        materialOnSurface = Color(0xFFF0EAE3),
        materialSurfaceVariant = Color(0xFF3A322A),
        materialOnSurfaceVariant = Color(0xFFC5BAA8),
        materialOutline = Color(0x33E0C8A8)
    ),
    Forest(
        key = "forest",
        label = "Forest",
        subtitle = "Rich green and teal",
        accentLabel = "Green",
        night = Color(0xFF0E1410),
        nightRaised = Color(0xFF171E18),
        glass = Color(0x47232E26),
        glassStrong = Color(0x663A4838),
        glassBorder = Color(0x33A0C8A0),
        accent = Color(0xFF7ACC8A),
        accentSecondary = Color(0xFF6AB8B8),
        accentTertiary = Color(0xFFB0CC6A),
        text = Color(0xFFE3F0E6),
        textMuted = Color(0xFFAFC5B2),
        materialPrimary = Color(0xFF7ACC8A),
        materialOnPrimary = Color(0xFF0E2612),
        materialPrimaryContainer = Color(0xFF26482A),
        materialOnPrimaryContainer = Color(0xFFD4F4DA),
        materialSecondary = Color(0xFF6AB8B8),
        materialOnSecondary = Color(0xFF0E2626),
        materialSecondaryContainer = Color(0xFF224848),
        materialOnSecondaryContainer = Color(0xFFD0F0F0),
        materialTertiary = Color(0xFFB0CC6A),
        materialOnTertiary = Color(0xFF1E2610),
        materialTertiaryContainer = Color(0xFF3A4826),
        materialOnTertiaryContainer = Color(0xFFEAF0D4),
        materialSurface = Color(0xFF171E18),
        materialOnSurface = Color(0xFFE3F0E6),
        materialSurfaceVariant = Color(0xFF2A382E),
        materialOnSurfaceVariant = Color(0xFFAFC5B2),
        materialOutline = Color(0x33A0C8A0)
    );

    companion object {
        fun fromKey(key: String): ThemeConfig = entries.firstOrNull { it.key == key } ?: Vault
    }
}

// Map theme accent color names to the existing color vals for backward compat
val ThemeConfig.VaultNight: Color get() = night
val ThemeConfig.VaultNightRaised: Color get() = nightRaised
val ThemeConfig.VaultGlass: Color get() = glass
val ThemeConfig.VaultGlassStrong: Color get() = glassStrong
val ThemeConfig.VaultGlassBorder: Color get() = glassBorder
val ThemeConfig.VaultMint: Color get() = accent
val ThemeConfig.VaultSky: Color get() = accentSecondary
val ThemeConfig.VaultAmber: Color get() = if (this == ThemeConfig.Ember) accentSecondary else accentTertiary
val ThemeConfig.VaultCoral: Color get() = if (this == ThemeConfig.Ember) accent else accentTertiary
val ThemeConfig.VaultText: Color get() = text
val ThemeConfig.VaultTextMuted: Color get() = textMuted
